name: Check env in python script

on:
  push:
    branches: [ main ]

jobs:
  envjob:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
         echo ${{ github.workspace }}
          
      - run: |
         val = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
         echo $val
         node --print 'process.env'
         
      - run: |
         echo $(python ${{ github.workspace }}/test.py)
